DROP TABLE IF EXISTS trips CASCADE;

CREATE TABLE trips(
    id SERIAL PRIMARY KEY NOT NULL,
    start_time TIMESTAMP,
    end_time TIMESTAMP,
    entry_id INTEGER REFERENCES entries(id) ON DELETE CASCADE
);